name: tic_tac_toe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_redux: ^0.9.0
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  meta: ^1.7.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.3
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.6
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true